### PR TITLE
fix: random* returning undefined vals when > collection size

### LINKED ISSUE #27: Unwanted behavior with random and randomKey methods
image
I don't think the above behavior is really the one wanted unless I'm wrong, so here's a suggested fix:
Last line of both methods: `return Array.from({ length: amount }, (): V => arr.splice(Math.floor(Math.random() * arr.length), 1)[0]);`
Replacement: `return Array.from({ length: Math.min(amount, arr.length) }, (): V => arr.splice(Math.floor(Math.random() * arr.length), 1)[0]);`

### PR DESCRIPTION
**Pull request by Fyko**
This PR updates the logic for `random*` functions when the number of random values requested is greater than the size of the collection.

Closes #27.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -273,6 +273,16 @@ test('random select from a collection', () => {
...
 });
 
+test('when random param > collection size', () => {
+	const coll = new Collection();
+	coll.set('a', 3);
+	coll.set('b', 2);
+	coll.set('c', 1);
+
+	const random = coll.random(5);
+	assert.ok(random.length === coll.size, "Random returned more elemants than the collection size");
```
Comment (vladfrangu) [inline test/index.js:283]:
```suggestion
	assert.ok(random.length === coll.size, "Random returned more elements than the collection size");
```

**Review by vladfrangu — CHANGES_REQUESTED** [review]

**Review by iCrawl — APPROVED** [review]
